language: node_js
node_js:
 - "0.11"
 - "0.10"
before_install:
 - "npm install --global gulp"
install:
 - "npm install"
 - "npm install -g typescript"
before_script:
script:
 - "tsc -p src"
 - "tsc -p test"